//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class BakerSterlingVortex : VortexModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BakerSterlingVortex(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PatternSolverPINVOKE.BakerSterlingVortex_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BakerSterlingVortex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(BakerSterlingVortex obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_BakerSterlingVortex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public BakerSterlingVortex(double Vr, double Vt, double Vs) : this(PatternSolverPINVOKE.new_BakerSterlingVortex__SWIG_0(Vr, Vt, Vs), true) {
  }

  public BakerSterlingVortex(double Vr, double Vt) : this(PatternSolverPINVOKE.new_BakerSterlingVortex__SWIG_1(Vr, Vt), true) {
  }

  public BakerSterlingVortex(double Vr) : this(PatternSolverPINVOKE.new_BakerSterlingVortex__SWIG_2(Vr), true) {
  }

  public BakerSterlingVortex() : this(PatternSolverPINVOKE.new_BakerSterlingVortex__SWIG_3(), true) {
  }

  public override SWIGTYPE_p_Vec2 vecAt(double x, double y) {
    SWIGTYPE_p_Vec2 ret = new SWIGTYPE_p_Vec2(PatternSolverPINVOKE.BakerSterlingVortex_vecAt(swigCPtr, x, y), true);
    return ret;
  }

  public override double patternLocation(double x) {
    double ret = PatternSolverPINVOKE.BakerSterlingVortex_patternLocation(swigCPtr, x);
    return ret;
  }

  public override bool patternLocationExists(double x) {
    bool ret = PatternSolverPINVOKE.BakerSterlingVortex_patternLocationExists(swigCPtr, x);
    return ret;
  }

}
