//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class ConvergenceLine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConvergenceLine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConvergenceLine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConvergenceLine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConvergenceLine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_ConvergenceLine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ConvergenceLine(DoubleVector points) : this(PatternSolverPINVOKE.new_ConvergenceLine__SWIG_0(DoubleVector.getCPtr(points)), true) {
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
  }

  public ConvergenceLine(string filePath) : this(PatternSolverPINVOKE.new_ConvergenceLine__SWIG_1(filePath), true) {
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
  }

  public DoubleVector query(double dist) {
    DoubleVector ret = new DoubleVector(PatternSolverPINVOKE.ConvergenceLine_query(swigCPtr, dist), true);
    return ret;
  }

  public double length() {
    double ret = PatternSolverPINVOKE.ConvergenceLine_length(swigCPtr);
    return ret;
  }

  public DoubleVector getXs() {
    DoubleVector ret = new DoubleVector(PatternSolverPINVOKE.ConvergenceLine_getXs(swigCPtr), true);
    return ret;
  }

  public DoubleVector getYs() {
    DoubleVector ret = new DoubleVector(PatternSolverPINVOKE.ConvergenceLine_getYs(swigCPtr), true);
    return ret;
  }

}
