//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class MatchResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MatchResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MatchResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MatchResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MatchResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_MatchResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DoubleVector minVels {
    set {
      PatternSolverPINVOKE.MatchResult_minVels_set(swigCPtr, DoubleVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.MatchResult_minVels_get(swigCPtr);
      DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
      return ret;
    } 
  }

  public DoubleVector bestSwirls {
    set {
      PatternSolverPINVOKE.MatchResult_bestSwirls_set(swigCPtr, DoubleVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.MatchResult_bestSwirls_get(swigCPtr);
      DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
      return ret;
    } 
  }

  public DoubleVector Rmaxs {
    set {
      PatternSolverPINVOKE.MatchResult_Rmaxs_set(swigCPtr, DoubleVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.MatchResult_Rmaxs_get(swigCPtr);
      DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
      return ret;
    } 
  }

  public void reserve(uint size) {
    PatternSolverPINVOKE.MatchResult_reserve(swigCPtr, size);
  }

  public void sort() {
    PatternSolverPINVOKE.MatchResult_sort(swigCPtr);
  }

  public void add(double minVel, double bestSwirl, double Rmax) {
    PatternSolverPINVOKE.MatchResult_add(swigCPtr, minVel, bestSwirl, Rmax);
  }

  public MatchResult() : this(PatternSolverPINVOKE.new_MatchResult(), true) {
  }

}
