//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class ModifiedRankineVortex : VortexModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ModifiedRankineVortex(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PatternSolverPINVOKE.ModifiedRankineVortex_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ModifiedRankineVortex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ModifiedRankineVortex obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_ModifiedRankineVortex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public double phi {
    set {
      PatternSolverPINVOKE.ModifiedRankineVortex_phi_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.ModifiedRankineVortex_phi_get(swigCPtr);
      return ret;
    } 
  }

  public ModifiedRankineVortex(double phi_, double Vr, double Vt, double Vs) : this(PatternSolverPINVOKE.new_ModifiedRankineVortex__SWIG_0(phi_, Vr, Vt, Vs), true) {
  }

  public ModifiedRankineVortex(double phi_, double Vr, double Vt) : this(PatternSolverPINVOKE.new_ModifiedRankineVortex__SWIG_1(phi_, Vr, Vt), true) {
  }

  public ModifiedRankineVortex(double phi_, double Vr) : this(PatternSolverPINVOKE.new_ModifiedRankineVortex__SWIG_2(phi_, Vr), true) {
  }

  public ModifiedRankineVortex(double phi_) : this(PatternSolverPINVOKE.new_ModifiedRankineVortex__SWIG_3(phi_), true) {
  }

  public override SWIGTYPE_p_Vec2 vecAt(double x, double y) {
    SWIGTYPE_p_Vec2 ret = new SWIGTYPE_p_Vec2(PatternSolverPINVOKE.ModifiedRankineVortex_vecAt(swigCPtr, x, y), true);
    return ret;
  }

}
