//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class Monitor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Monitor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Monitor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Monitor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Monitor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_Monitor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double value {
    set {
      PatternSolverPINVOKE.Monitor_value_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Monitor_value_get(swigCPtr);
      return ret;
    } 
  }

  public double min {
    set {
      PatternSolverPINVOKE.Monitor_min_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Monitor_min_get(swigCPtr);
      return ret;
    } 
  }

  public double max {
    set {
      PatternSolverPINVOKE.Monitor_max_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Monitor_max_get(swigCPtr);
      return ret;
    } 
  }

  public string title {
    set {
      PatternSolverPINVOKE.Monitor_title_set(swigCPtr, value);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = PatternSolverPINVOKE.Monitor_title_get(swigCPtr);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string message {
    set {
      PatternSolverPINVOKE.Monitor_message_set(swigCPtr, value);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = PatternSolverPINVOKE.Monitor_message_get(swigCPtr);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string warning {
    set {
      PatternSolverPINVOKE.Monitor_warning_set(swigCPtr, value);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = PatternSolverPINVOKE.Monitor_warning_get(swigCPtr);
      if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool cancelled {
    set {
      PatternSolverPINVOKE.Monitor_cancelled_set(swigCPtr, value);
    } 
    get {
      bool ret = PatternSolverPINVOKE.Monitor_cancelled_get(swigCPtr);
      return ret;
    } 
  }

  public Monitor() : this(PatternSolverPINVOKE.new_Monitor(), true) {
  }

}
