//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class PatternSolverPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="SWIGRegisterExceptionCallbacks_PatternSolver")]
    public static extern void SWIGRegisterExceptionCallbacks_PatternSolver(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_PatternSolver")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_PatternSolver(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_PatternSolver(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_PatternSolver(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="SWIGRegisterStringCallback_PatternSolver")]
    public static extern void SWIGRegisterStringCallback_PatternSolver(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_PatternSolver(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static PatternSolverPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_DoubleVector__SWIG_0")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_DoubleVector__SWIG_1")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Clear")]
  public static extern void DoubleVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Add")]
  public static extern void DoubleVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_size")]
  public static extern uint DoubleVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_empty")]
  public static extern bool DoubleVector_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_capacity")]
  public static extern uint DoubleVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_reserve")]
  public static extern void DoubleVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_DoubleVector__SWIG_2")]
  public static extern global::System.IntPtr new_DoubleVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_getitemcopy")]
  public static extern double DoubleVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_getitem")]
  public static extern double DoubleVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_setitem")]
  public static extern void DoubleVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_AddRange")]
  public static extern void DoubleVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_GetRange")]
  public static extern global::System.IntPtr DoubleVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Insert")]
  public static extern void DoubleVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_InsertRange")]
  public static extern void DoubleVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_RemoveAt")]
  public static extern void DoubleVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_RemoveRange")]
  public static extern void DoubleVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Repeat")]
  public static extern global::System.IntPtr DoubleVector_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Reverse__SWIG_0")]
  public static extern void DoubleVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Reverse__SWIG_1")]
  public static extern void DoubleVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_SetRange")]
  public static extern void DoubleVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Contains")]
  public static extern bool DoubleVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_IndexOf")]
  public static extern int DoubleVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_LastIndexOf")]
  public static extern int DoubleVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_DoubleVector_Remove")]
  public static extern bool DoubleVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_DoubleVector")]
  public static extern void delete_DoubleVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_createSpan")]
  public static extern global::System.IntPtr createSpan(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_getSpanSize")]
  public static extern int getSpanSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_getSpanPtr")]
  public static extern global::System.IntPtr getSpanPtr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_freeSpan")]
  public static extern void freeSpan(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_createVector")]
  public static extern global::System.IntPtr createVector(global::System.IntPtr jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_getVector")]
  public static extern global::System.IntPtr getVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Range_min_set")]
  public static extern void Range_min_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Range_min_get")]
  public static extern double Range_min_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Range_max_set")]
  public static extern void Range_max_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Range_max_get")]
  public static extern double Range_max_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Range_random")]
  public static extern double Range_random(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Range")]
  public static extern global::System.IntPtr new_Range();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Range")]
  public static extern void delete_Range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_writeBinaryFile")]
  public static extern void writeBinaryFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_readBinaryFile")]
  public static extern global::System.IntPtr readBinaryFile(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Curve_xs_set")]
  public static extern void Curve_xs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Curve_xs_get")]
  public static extern global::System.IntPtr Curve_xs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Curve_ys_set")]
  public static extern void Curve_ys_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Curve_ys_get")]
  public static extern global::System.IntPtr Curve_ys_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Curve_reserve")]
  public static extern void Curve_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Curve")]
  public static extern global::System.IntPtr new_Curve();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Curve")]
  public static extern void delete_Curve(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_vecs_set")]
  public static extern void Pattern_vecs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_vecs_get")]
  public static extern global::System.IntPtr Pattern_vecs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_dx_set")]
  public static extern void Pattern_dx_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_dx_get")]
  public static extern double Pattern_dx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_lower_set")]
  public static extern void Pattern_lower_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_lower_get")]
  public static extern double Pattern_lower_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_upper_set")]
  public static extern void Pattern_upper_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_upper_get")]
  public static extern double Pattern_upper_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_Xc_set")]
  public static extern void Pattern_Xc_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_Xc_get")]
  public static extern double Pattern_Xc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Pattern__SWIG_0")]
  public static extern global::System.IntPtr new_Pattern__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Pattern__SWIG_1")]
  public static extern global::System.IntPtr new_Pattern__SWIG_1(double jarg1, double jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_reserve")]
  public static extern void Pattern_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Pattern_insert")]
  public static extern void Pattern_insert(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Pattern")]
  public static extern void delete_Pattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vr_set")]
  public static extern void VortexModel_Vr_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vr_get")]
  public static extern double VortexModel_Vr_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vt_set")]
  public static extern void VortexModel_Vt_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vt_get")]
  public static extern double VortexModel_Vt_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vs_set")]
  public static extern void VortexModel_Vs_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Vs_get")]
  public static extern double VortexModel_Vs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_lower_set")]
  public static extern void VortexModel_lower_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_lower_get")]
  public static extern double VortexModel_lower_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_upper_set")]
  public static extern void VortexModel_upper_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_upper_get")]
  public static extern double VortexModel_upper_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Xc_set")]
  public static extern void VortexModel_Xc_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_Xc_get")]
  public static extern double VortexModel_Xc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_vecAt")]
  public static extern global::System.IntPtr VortexModel_vecAt(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_patternLocation")]
  public static extern double VortexModel_patternLocation(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_solveAxesOfInterest")]
  public static extern void VortexModel_solveAxesOfInterest(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_length")]
  public static extern double VortexModel_length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_lengthAbove")]
  public static extern double VortexModel_lengthAbove(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_lengthBelow")]
  public static extern double VortexModel_lengthBelow(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_vmax")]
  public static extern double VortexModel_vmax(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_hasPattern")]
  public static extern bool VortexModel_hasPattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_unitVecAt")]
  public static extern global::System.IntPtr VortexModel_unitVecAt(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_patternVec")]
  public static extern global::System.IntPtr VortexModel_patternVec(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_magAt")]
  public static extern double VortexModel_magAt(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_swirlRatio")]
  public static extern double VortexModel_swirlRatio(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_field__SWIG_0")]
  public static extern global::System.IntPtr VortexModel_field__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_field__SWIG_1")]
  public static extern global::System.IntPtr VortexModel_field__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_patternCurve")]
  public static extern global::System.IntPtr VortexModel_patternCurve(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_pattern__SWIG_0")]
  public static extern global::System.IntPtr VortexModel_pattern__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexModel_pattern__SWIG_1")]
  public static extern global::System.IntPtr VortexModel_pattern__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_VortexModel")]
  public static extern void delete_VortexModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_LinearPiecewiseVortex__SWIG_0")]
  public static extern global::System.IntPtr new_LinearPiecewiseVortex__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_LinearPiecewiseVortex__SWIG_1")]
  public static extern global::System.IntPtr new_LinearPiecewiseVortex__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_LinearPiecewiseVortex__SWIG_2")]
  public static extern global::System.IntPtr new_LinearPiecewiseVortex__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_LinearPiecewiseVortex_vecAt")]
  public static extern global::System.IntPtr LinearPiecewiseVortex_vecAt(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_LinearPiecewiseVortex_patternLocation")]
  public static extern double LinearPiecewiseVortex_patternLocation(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_LinearPiecewiseVortex")]
  public static extern void delete_LinearPiecewiseVortex(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_gridSize_get")]
  public static extern int gridSize_get();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_xmin_set")]
  public static extern void VecHashGrid_xmin_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_xmin_get")]
  public static extern double VecHashGrid_xmin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_xmax_set")]
  public static extern void VecHashGrid_xmax_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_xmax_get")]
  public static extern double VecHashGrid_xmax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_ymin_set")]
  public static extern void VecHashGrid_ymin_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_ymin_get")]
  public static extern double VecHashGrid_ymin_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_ymax_set")]
  public static extern void VecHashGrid_ymax_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_ymax_get")]
  public static extern double VecHashGrid_ymax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_VecHashGrid__SWIG_0")]
  public static extern global::System.IntPtr new_VecHashGrid__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_VecHashGrid__SWIG_1")]
  public static extern global::System.IntPtr new_VecHashGrid__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_insert")]
  public static extern void VecHashGrid_insert(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_query__SWIG_0")]
  public static extern global::System.IntPtr VecHashGrid_query__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_query__SWIG_1")]
  public static extern global::System.IntPtr VecHashGrid_query__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_vectors")]
  public static extern global::System.IntPtr VecHashGrid_vectors(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VecHashGrid_counts")]
  public static extern global::System.IntPtr VecHashGrid_counts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_VecHashGrid")]
  public static extern void delete_VecHashGrid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_ConvergenceLine__SWIG_0")]
  public static extern global::System.IntPtr new_ConvergenceLine__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_ConvergenceLine__SWIG_1")]
  public static extern global::System.IntPtr new_ConvergenceLine__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ConvergenceLine_query")]
  public static extern global::System.IntPtr ConvergenceLine_query(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ConvergenceLine_length")]
  public static extern double ConvergenceLine_length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ConvergenceLine_getXs")]
  public static extern global::System.IntPtr ConvergenceLine_getXs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ConvergenceLine_getYs")]
  public static extern global::System.IntPtr ConvergenceLine_getYs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_ConvergenceLine")]
  public static extern void delete_ConvergenceLine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PI_get")]
  public static extern double PI_get();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_x_set")]
  public static extern void Rect_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_x_get")]
  public static extern double Rect_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_y_set")]
  public static extern void Rect_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_y_get")]
  public static extern double Rect_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_w_set")]
  public static extern void Rect_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_w_get")]
  public static extern double Rect_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_h_set")]
  public static extern void Rect_h_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Rect_h_get")]
  public static extern double Rect_h_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Rect")]
  public static extern global::System.IntPtr new_Rect();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Rect")]
  public static extern void delete_Rect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_x_set")]
  public static extern void Transect_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_x_get")]
  public static extern double Transect_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_y_set")]
  public static extern void Transect_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_y_get")]
  public static extern double Transect_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_theta_set")]
  public static extern void Transect_theta_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_theta_get")]
  public static extern double Transect_theta_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_lengthAbove_set")]
  public static extern void Transect_lengthAbove_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_lengthAbove_get")]
  public static extern double Transect_lengthAbove_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_lengthBelow_set")]
  public static extern void Transect_lengthBelow_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_lengthBelow_get")]
  public static extern double Transect_lengthBelow_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_width_set")]
  public static extern void Transect_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_width_get")]
  public static extern double Transect_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_positionOffset_set")]
  public static extern void Transect_positionOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_positionOffset_get")]
  public static extern double Transect_positionOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_heightOffset_set")]
  public static extern void Transect_heightOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_heightOffset_get")]
  public static extern double Transect_heightOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_angleOffset_set")]
  public static extern void Transect_angleOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_angleOffset_get")]
  public static extern double Transect_angleOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_spacing_set")]
  public static extern void Transect_spacing_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_spacing_get")]
  public static extern double Transect_spacing_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_name_set")]
  public static extern void Transect_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_name_get")]
  public static extern string Transect_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Transect__SWIG_0")]
  public static extern global::System.IntPtr new_Transect__SWIG_0(double jarg1, double jarg2, double jarg3, double jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Transect__SWIG_1")]
  public static extern global::System.IntPtr new_Transect__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Transect__SWIG_2")]
  public static extern global::System.IntPtr new_Transect__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_setPerpendicularAngle")]
  public static extern void Transect_setPerpendicularAngle(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_center")]
  public static extern global::System.IntPtr Transect_center(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_normRect")]
  public static extern global::System.IntPtr Transect_normRect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Transect_extent")]
  public static extern global::System.IntPtr Transect_extent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Transect")]
  public static extern void delete_Transect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_vecs_set")]
  public static extern void ObservedPattern_vecs_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_vecs_get")]
  public static extern global::System.IntPtr ObservedPattern_vecs_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_lengthAbove_set")]
  public static extern void ObservedPattern_lengthAbove_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_lengthAbove_get")]
  public static extern double ObservedPattern_lengthAbove_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_lengthBelow_set")]
  public static extern void ObservedPattern_lengthBelow_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_lengthBelow_get")]
  public static extern double ObservedPattern_lengthBelow_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_spacing_set")]
  public static extern void ObservedPattern_spacing_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_spacing_get")]
  public static extern double ObservedPattern_spacing_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_ObservedPattern")]
  public static extern global::System.IntPtr new_ObservedPattern(double jarg1, double jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_length")]
  public static extern double ObservedPattern_length(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_size")]
  public static extern int ObservedPattern_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_centerIdx")]
  public static extern int ObservedPattern_centerIdx(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_vectors")]
  public static extern global::System.IntPtr ObservedPattern_vectors(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_isMissingVectors")]
  public static extern bool ObservedPattern_isMissingVectors(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_isConverging")]
  public static extern bool ObservedPattern_isConverging(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_isUnchanging")]
  public static extern bool ObservedPattern_isUnchanging(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_isSimulatableType")]
  public static extern bool ObservedPattern_isSimulatableType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_ObservedPattern_isValid")]
  public static extern bool ObservedPattern_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_ObservedPattern")]
  public static extern void delete_ObservedPattern(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_positionOffsetRange_set")]
  public static extern void AutoTransectFitter_positionOffsetRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_positionOffsetRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_positionOffsetRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_lengthAboveRange_set")]
  public static extern void AutoTransectFitter_lengthAboveRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_lengthAboveRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_lengthAboveRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_lengthBelowRange_set")]
  public static extern void AutoTransectFitter_lengthBelowRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_lengthBelowRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_lengthBelowRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_angleOffsetRange_set")]
  public static extern void AutoTransectFitter_angleOffsetRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_angleOffsetRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_angleOffsetRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_heightOffsetRange_set")]
  public static extern void AutoTransectFitter_heightOffsetRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_heightOffsetRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_heightOffsetRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_widthRange_set")]
  public static extern void AutoTransectFitter_widthRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_widthRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_widthRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_spacingRange_set")]
  public static extern void AutoTransectFitter_spacingRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_spacingRange_get")]
  public static extern global::System.IntPtr AutoTransectFitter_spacingRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_monitor_set")]
  public static extern void AutoTransectFitter_monitor_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_monitor_get")]
  public static extern global::System.IntPtr AutoTransectFitter_monitor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_matchThreshold_set")]
  public static extern void AutoTransectFitter_matchThreshold_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_matchThreshold_get")]
  public static extern double AutoTransectFitter_matchThreshold_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_maxIters_set")]
  public static extern void AutoTransectFitter_maxIters_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_maxIters_get")]
  public static extern int AutoTransectFitter_maxIters_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_failed_set")]
  public static extern void AutoTransectFitter_failed_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_failed_get")]
  public static extern bool AutoTransectFitter_failed_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_AutoTransectFitter")]
  public static extern global::System.IntPtr new_AutoTransectFitter(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_resultsSize")]
  public static extern int AutoTransectFitter_resultsSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_getResult")]
  public static extern global::System.IntPtr AutoTransectFitter_getResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_randomClusterSearch")]
  public static extern void AutoTransectFitter_randomClusterSearch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_AutoTransectFitter_randomSearch")]
  public static extern global::System.IntPtr AutoTransectFitter_randomSearch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_AutoTransectFitter")]
  public static extern void delete_AutoTransectFitter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VrRange_set")]
  public static extern void PatternMatcher_VrRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VrRange_get")]
  public static extern global::System.IntPtr PatternMatcher_VrRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VtRange_set")]
  public static extern void PatternMatcher_VtRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VtRange_get")]
  public static extern global::System.IntPtr PatternMatcher_VtRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VsRange_set")]
  public static extern void PatternMatcher_VsRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VsRange_get")]
  public static extern global::System.IntPtr PatternMatcher_VsRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VcRange_set")]
  public static extern void PatternMatcher_VcRange_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_VcRange_get")]
  public static extern global::System.IntPtr PatternMatcher_VcRange_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_monitor_set")]
  public static extern void PatternMatcher_monitor_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_monitor_get")]
  public static extern global::System.IntPtr PatternMatcher_monitor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_matchThreshold_set")]
  public static extern void PatternMatcher_matchThreshold_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_matchThreshold_get")]
  public static extern double PatternMatcher_matchThreshold_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_numSimulations_set")]
  public static extern void PatternMatcher_numSimulations_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_numSimulations_get")]
  public static extern int PatternMatcher_numSimulations_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestMatchScale_set")]
  public static extern void PatternMatcher_bestMatchScale_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestMatchScale_get")]
  public static extern double PatternMatcher_bestMatchScale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_minVelResults_set")]
  public static extern void PatternMatcher_minVelResults_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_minVelResults_get")]
  public static extern global::System.IntPtr PatternMatcher_minVelResults_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestSwirlResults_set")]
  public static extern void PatternMatcher_bestSwirlResults_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestSwirlResults_get")]
  public static extern global::System.IntPtr PatternMatcher_bestSwirlResults_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_PatternMatcher")]
  public static extern global::System.IntPtr new_PatternMatcher(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestMatchError")]
  public static extern double PatternMatcher_bestMatchError(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_bestMatch")]
  public static extern global::System.IntPtr PatternMatcher_bestMatch(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_PatternMatcher_monteCarloMatching")]
  public static extern void PatternMatcher_monteCarloMatching(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_PatternMatcher")]
  public static extern void delete_PatternMatcher(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexFactory_bakerSterlingVortex")]
  public static extern global::System.IntPtr VortexFactory_bakerSterlingVortex(double jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_VortexFactory_BakerSterlingLPVortex")]
  public static extern global::System.IntPtr VortexFactory_BakerSterlingLPVortex(double jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_VortexFactory")]
  public static extern global::System.IntPtr new_VortexFactory();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_VortexFactory")]
  public static extern void delete_VortexFactory(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_value_set")]
  public static extern void Monitor_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_value_get")]
  public static extern double Monitor_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_min_set")]
  public static extern void Monitor_min_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_min_get")]
  public static extern double Monitor_min_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_max_set")]
  public static extern void Monitor_max_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_max_get")]
  public static extern double Monitor_max_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_title_set")]
  public static extern void Monitor_title_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_title_get")]
  public static extern string Monitor_title_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_message_set")]
  public static extern void Monitor_message_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_message_get")]
  public static extern string Monitor_message_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_warning_set")]
  public static extern void Monitor_warning_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_warning_get")]
  public static extern string Monitor_warning_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_cancelled_set")]
  public static extern void Monitor_cancelled_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_Monitor_cancelled_get")]
  public static extern bool Monitor_cancelled_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_new_Monitor")]
  public static extern global::System.IntPtr new_Monitor();

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_delete_Monitor")]
  public static extern void delete_Monitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("PatternSolver", EntryPoint="CSharp_LinearPiecewiseVortex_SWIGUpcast")]
  public static extern global::System.IntPtr LinearPiecewiseVortex_SWIGUpcast(global::System.IntPtr jarg1);
}
