//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class Range : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Range(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Range obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Range obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Range() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_Range(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double min {
    set {
      PatternSolverPINVOKE.Range_min_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Range_min_get(swigCPtr);
      return ret;
    } 
  }

  public double max {
    set {
      PatternSolverPINVOKE.Range_max_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Range_max_get(swigCPtr);
      return ret;
    } 
  }

  public double random(SWIGTYPE_p_std__uniform_real_distributionT_double_t dist, SWIGTYPE_p_std__mt19937 gen) {
    double ret = PatternSolverPINVOKE.Range_random(swigCPtr, SWIGTYPE_p_std__uniform_real_distributionT_double_t.getCPtr(dist), SWIGTYPE_p_std__mt19937.getCPtr(gen));
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Range() : this(PatternSolverPINVOKE.new_Range(), true) {
  }

}
