//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class Rect : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Rect(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Rect obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Rect obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Rect() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_Rect(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double x {
    set {
      PatternSolverPINVOKE.Rect_x_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Rect_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      PatternSolverPINVOKE.Rect_y_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Rect_y_get(swigCPtr);
      return ret;
    } 
  }

  public double w {
    set {
      PatternSolverPINVOKE.Rect_w_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Rect_w_get(swigCPtr);
      return ret;
    } 
  }

  public double h {
    set {
      PatternSolverPINVOKE.Rect_h_set(swigCPtr, value);
    } 
    get {
      double ret = PatternSolverPINVOKE.Rect_h_get(swigCPtr);
      return ret;
    } 
  }

  public Rect() : this(PatternSolverPINVOKE.new_Rect(), true) {
  }

}
