//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class TransectRandomizer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TransectRandomizer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TransectRandomizer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TransectRandomizer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TransectRandomizer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PatternSolverPINVOKE.delete_TransectRandomizer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Range positionOffsetRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_positionOffsetRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_positionOffsetRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range lengthAboveRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_lengthAboveRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_lengthAboveRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range lengthBelowRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_lengthBelowRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_lengthBelowRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range angleOffsetRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_angleOffsetRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_angleOffsetRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range heightOffsetRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_heightOffsetRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_heightOffsetRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range widthRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_widthRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_widthRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public Range spacingRange {
    set {
      PatternSolverPINVOKE.TransectRandomizer_spacingRange_set(swigCPtr, Range.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = PatternSolverPINVOKE.TransectRandomizer_spacingRange_get(swigCPtr);
      Range ret = (cPtr == global::System.IntPtr.Zero) ? null : new Range(cPtr, false);
      return ret;
    } 
  }

  public TransectRandomizer(VecHashGrid vectorHashGrid, ConvergenceLine convergenceLine) : this(PatternSolverPINVOKE.new_TransectRandomizer__SWIG_0(VecHashGrid.getCPtr(vectorHashGrid), ConvergenceLine.getCPtr(convergenceLine)), true) {
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
  }

  public TransectRandomizer(Transect transect, VecHashGrid vectorHashGrid, ConvergenceLine convergenceLine) : this(PatternSolverPINVOKE.new_TransectRandomizer__SWIG_1(Transect.getCPtr(transect), VecHashGrid.getCPtr(vectorHashGrid), ConvergenceLine.getCPtr(convergenceLine)), true) {
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
  }

  public ObservedPattern rand(SWIGTYPE_p_std__uniform_real_distributionT_double_t dist, SWIGTYPE_p_std__mt19937 gen) {
    ObservedPattern ret = new ObservedPattern(PatternSolverPINVOKE.TransectRandomizer_rand(swigCPtr, SWIGTYPE_p_std__uniform_real_distributionT_double_t.getCPtr(dist), SWIGTYPE_p_std__mt19937.getCPtr(gen)), true);
    if (PatternSolverPINVOKE.SWIGPendingException.Pending) throw PatternSolverPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
